# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/sbin/cmake

# The command to remove a file.
RM = /usr/sbin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zafod/Programming/computer_graphics/lab1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zafod/Programming/computer_graphics/lab1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/sbin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/sbin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zafod/Programming/computer_graphics/lab1/CMakeFiles /home/zafod/Programming/computer_graphics/lab1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zafod/Programming/computer_graphics/lab1/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zafod/Programming/computer_graphics/lab1/CMakeFiles /home/zafod/Programming/computer_graphics/lab1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zafod/Programming/computer_graphics/lab1/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpenGLTemplate

# Build rule for target.
OpenGLTemplate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OpenGLTemplate
.PHONY : OpenGLTemplate

# fast build rule for target.
OpenGLTemplate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenGLTemplate.dir/build.make CMakeFiles/OpenGLTemplate.dir/build
.PHONY : OpenGLTemplate/fast

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenGLTemplate.dir/build.make CMakeFiles/OpenGLTemplate.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenGLTemplate.dir/build.make CMakeFiles/OpenGLTemplate.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenGLTemplate.dir/build.make CMakeFiles/OpenGLTemplate.dir/main.cc.s
.PHONY : main.cc.s

usr/src/gl.o: usr/src/gl.c.o
.PHONY : usr/src/gl.o

# target to build an object file
usr/src/gl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenGLTemplate.dir/build.make CMakeFiles/OpenGLTemplate.dir/usr/src/gl.c.o
.PHONY : usr/src/gl.c.o

usr/src/gl.i: usr/src/gl.c.i
.PHONY : usr/src/gl.i

# target to preprocess a source file
usr/src/gl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenGLTemplate.dir/build.make CMakeFiles/OpenGLTemplate.dir/usr/src/gl.c.i
.PHONY : usr/src/gl.c.i

usr/src/gl.s: usr/src/gl.c.s
.PHONY : usr/src/gl.s

# target to generate assembly for a file
usr/src/gl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenGLTemplate.dir/build.make CMakeFiles/OpenGLTemplate.dir/usr/src/gl.c.s
.PHONY : usr/src/gl.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... OpenGLTemplate"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... usr/src/gl.o"
	@echo "... usr/src/gl.i"
	@echo "... usr/src/gl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

